### ISSUE TITLE
Try to run pc_opt.py but get errors

### ISSUE THREAD

**Issue by Vilour** [yizhangphd/FreqPCR#4]
Great works! I tried to run the code with the instruction but failed. What could be wrong?
I ran with 
`python pc_opt.py --config=configs/pc_opt/nerf_hotdog.txt `
get errors
```
patch too small!
patch too small!
patch too small!
patch too small!
patch too small!
patch too small!
patch too small!
patch too small!
patch too small!
patch too small!
patch too small!
patch too small!
patch too small!
too many!! break!
Done. adding num:2473640
[Open3D WARNING] Write PLY failed: point cloud has 0 points.
100%|##########| 1/1 [00:00<00:00, 19.92it/s]
100%|##########| 100/100 [00:04<00:00, 23.42it/s]
[16:58:55] Rasterize Finish
Traceback (most recent call last):
  File "/home/User/FreqPCR/pc_opt.py", line 184, in <module>
    img_pre, acc_pre, dep, gt = renderer(zbuf, ray, idbuf, True, torch.cat([img_gt, alpha_gt], dim=-1))
  File "/home/User/anaconda3/envs/FreqPCR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/User/FreqPCR/model/renderer.py", line 179, in forward
    sigma_map = sigma[idx] # B, H, W, K, 1
IndexError: index is out of bounds for dimension with size 0
```

**Comment by Vilour** [comment]
Stupid mistake. Sorry to bother
